language: python
python:
    - 2.6
    - 2.7
install:
    - pip install -r requirements_dev.txt
    - python setup.py install
sudo: false
script: python setup.py nosetests
before_install:
  - pip install codecov
after_success:
  - codecov
branches:
    only:
        - master
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - andrew@topdog.za.net
